"""Junction CONTROL: the lock, hand-edited membership, and span junctions (#319).

A junction generated by RoadMaker is AUTOMATIC — it re-derives itself from the
roads that meet it every time one of them is edited. `edit.set_junction_locked`
takes a junction out of that loop so hand-tuned connections, corners and stop
lines survive; `regenerate_junction` still re-derives it on demand, so the lock
guards the automatic pass rather than freezing the junction.

The lock is also a PRECONDITION for editing membership: `add_junction_arm`,
`remove_junction_arm` and `merge_junctions` refuse an unlocked junction, because
the next automatic pass would re-derive the arm list and undo the edit. Unlocking
hands the junction back — and when its arms no longer plan there is nothing to
hand back to, so the unlock removes the junction instead.

`edit.create_span_junction` covers the other kind entirely: a SPAN (virtual)
junction per ASAM OpenDRIVE 1.9.0 §12.7 (identical in 1.8.1 §12.7). It marks a
stretch of an UNINTERRUPTED road — a mid-road crosswalk, or the same crossing
over two parallel carriageways — so it has no arms, no connecting roads and no
road links at all, and it is always locked. It persists as a spec-valid
`<junction type="virtual" mainRoad=… orientation="none" sStart=… sEnd=…>` with
the full span list on `<userData code="rm:spans">`.

Every step below is ONE undoable command, and every step is checked for a
byte-identical save → reload → save.

Run:  python junction_control.py [out.xodr]
"""

from __future__ import annotations

import sys

import roadmaker as rm

NAME = "junction_control"


def road_names(network: rm.RoadNetwork, junction: rm.JunctionId) -> str:
    """The odr ids of a junction's arm roads, in arm order."""
    return ", ".join(network.road(arm.road).odr_id for arm in network.junction(junction).arms)


def describe(network: rm.RoadNetwork, label: str) -> None:
    print(f"\n{label}")
    for jid in network.junction_ids:
        junction = network.junction(jid)
        lock = "LOCKED  " if junction.locked else "automatic"
        if junction.spans:
            spans = " ".join(
                f"{network.road(s.road).odr_id}[{s.s_start:g}..{s.s_end:g}]"
                for s in junction.spans
            )
            print(f"  junction {junction.odr_id}: {lock} span (virtual) over {spans}")
        else:
            print(
                f"  junction {junction.odr_id}: {lock} arms=({road_names(network, jid)}) "
                f"{len(junction.connections)} connecting roads"
            )


def check_round_trip(network: rm.RoadNetwork, step: str) -> None:
    """save -> reload -> save must be byte-identical, and reload must be silent."""
    text = rm.write_xodr(network, NAME)
    reloaded, diagnostics = rm.parse_xodr(text)
    assert not diagnostics, f"{step}: {[d.message for d in diagnostics]}"
    again = rm.write_xodr(reloaded, NAME)
    assert again == text, f"{step}: save->reload->save is not byte-identical"
    print(f"  [round trip ok] {step} — {len(text)} bytes, no diagnostics")


def straight(stack: rm.edit.EditStack, network: rm.RoadNetwork, a, b) -> None:
    stack.push(network, rm.edit.create_road([a, b], rm.LaneProfile.two_lane_default(), ""))


def main() -> int:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "junction_control.xodr"

    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()

    # --- 1. a small network -------------------------------------------------
    # Two clusters that will end up merged, plus two through roads well away
    # from them that the span junctions will cover.
    straight(stack, network, (-90.0, 0.0), (-15.0, 0.0))     # "1" west
    straight(stack, network, (0.0, -90.0), (0.0, -15.0))     # "2" south
    straight(stack, network, (0.0, 90.0), (0.0, 15.0))       # "3" north
    straight(stack, network, (90.0, 0.0), (15.0, 0.0))       # "4" east
    straight(stack, network, (90.0, 90.0), (15.0, 15.0))     # "5" north-east
    straight(stack, network, (0.0, -200.0), (120.0, -200.0)) # "6" carriageway A
    straight(stack, network, (0.0, -212.0), (120.0, -212.0)) # "7" carriageway B
    straight(stack, network, (0.0, -260.0), (120.0, -260.0)) # "8" single road
    print(f"authored {len(network.road_ids)} roads")

    def end(odr: str) -> rm.RoadEnd:
        return rm.RoadEnd(network.find_road(odr), rm.ContactPoint.END)

    # --- 2. two automatic junctions ----------------------------------------
    stack.push(network, rm.edit.create_junction(network, [end("1"), end("2")]))
    left = network.find_junction("1")
    stack.push(network, rm.edit.create_junction(network, [end("4"), end("5")]))
    right = network.find_junction("2")
    describe(network, "two generated junctions — both automatic:")
    check_round_trip(network, "generated")

    # --- 3. lock ------------------------------------------------------------
    # A pure value edit: the turn set is untouched, so the editor must NOT
    # regenerate on top of it.
    stack.push(network, rm.edit.set_junction_locked(network, left, True))
    describe(network, "after locking junction 1:")
    check_round_trip(network, "locked")

    # Membership edits are refused while a junction is automatic.
    try:
        stack.push(network, rm.edit.add_junction_arm(network, right, end("3")))
    except ValueError as error:
        print(f"\nadd_junction_arm on the UNLOCKED junction 2 refused: {error}")

    # --- 4. add an arm ------------------------------------------------------
    # Road "3" joins junction 1 by hand: its link slot is claimed and the turns
    # it opens get fresh connecting roads. Surviving turns keep their ids.
    stack.push(network, rm.edit.add_junction_arm(network, left, end("3")))
    describe(network, "after add_junction_arm(junction 1, road 3 end):")
    check_round_trip(network, "arm added")

    # --- 5. merge the neighbouring junction --------------------------------
    # One junction over the union of both arm lists. The survivor keeps its odr
    # id, name, corners and stop lines; the absorbed junction is erased in place
    # so undo restores it under its own id. The result is LOCKED.
    stack.push(network, rm.edit.merge_junctions(network, left, right))
    describe(network, "after merge_junctions(survivor=1, absorbed=2):")
    check_round_trip(network, "merged")

    # Undo/redo — one command, exactly reversible.
    stack.undo(network)
    assert len(network.junction_ids) == 2, "undo brings the absorbed junction back"
    stack.redo(network)
    assert len(network.junction_ids) == 1
    print("\nundo/redo of the merge restored and re-absorbed junction 2")

    # --- 6. unlock ----------------------------------------------------------
    # The union still plans, so unlocking is a value edit that hands the
    # junction back to the automatic loop. (Had the arms drifted out of reach
    # there would be nothing to hand back to, and the unlock would REMOVE the
    # junction together with its connecting roads.)
    stack.push(network, rm.edit.set_junction_locked(network, left, False))
    describe(network, "after unlocking the merged junction:")
    check_round_trip(network, "unlocked")

    # --- 7. span (virtual) junctions ---------------------------------------
    # §12.7: the main road is UNINTERRUPTED. Nothing is cut, nothing is linked,
    # no connecting road is generated — the junction record simply declares that
    # [s_start, s_end] of the named road(s) is junction area. It is always
    # locked, because there is no derivation behind it to re-run.
    crosswalk = [rm.SpanArm(network.find_road("8"), 50.0, 56.5)]
    stack.push(network, rm.edit.create_span_junction(network, crosswalk))

    dual = [
        rm.SpanArm(network.find_road("6"), 40.0, 44.0),
        rm.SpanArm(network.find_road("7"), 41.5, 45.5),
    ]
    stack.push(network, rm.edit.create_span_junction(network, dual))
    describe(network, "after create_span_junction (single road, then two parallel roads):")
    check_round_trip(network, "span junctions")

    covered = network.junction(network.junction_ids[-1])
    assert covered.locked and not covered.arms and not covered.connections
    assert not network.road(network.find_road("6")).predecessor
    assert not network.road(network.find_road("6")).successor
    print("\nthe span junction has no arms, no connections and no road links —")
    print("road 6 is still one uninterrupted road, exactly as §12.7 requires")

    # A span junction's lock is structural, not a preference.
    try:
        stack.push(network, rm.edit.set_junction_locked(network, network.junction_ids[-1], False))
    except ValueError as error:
        print(f"unlocking a span junction refused: {error}")

    # What the factory refuses.
    for label, spans in (
        ("no spans", []),
        ("three spans", dual + crosswalk),
        ("inverted", [rm.SpanArm(network.find_road("8"), 60.0, 40.0)]),
        ("past the road end", [rm.SpanArm(network.find_road("8"), 100.0, 500.0)]),
        ("the same road twice", [
            rm.SpanArm(network.find_road("8"), 10.0, 14.0),
            rm.SpanArm(network.find_road("8"), 20.0, 24.0),
        ]),
    ):
        try:
            stack.push(network, rm.edit.create_span_junction(network, spans))
            raise AssertionError(f"{label} should have been refused")
        except ValueError as error:
            print(f"  refused ({label}): {error}")

    # --- 8. save ------------------------------------------------------------
    findings = rm.validate_network(network)
    print(f"\nvalidate_network: {len(findings)} findings")
    for finding in findings:
        print(f"  {finding.severity} {finding.location}: {finding.message}")
    assert not findings

    rm.save_xodr(network, out_path, NAME)
    virtual = sum(1 for line in open(out_path) if 'type="virtual"' in line)
    print(f"wrote {out_path} — {virtual} virtual junctions, {len(network.road_ids)} roads")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
