"""RoadMaker: road-network authoring for AV simulation.

C++ kernel with ASAM OpenDRIVE I/O, clothoid authoring, mesh generation,
and glTF export. See https://github.com/robomous/roadmaker.
"""

from ._roadmaker import (  # noqa: F401
    BoundarySource,
    ContactPoint,
    CrosswalkData,
    Diagnostic,
    Junction,
    JunctionCorner,
    JunctionCornerInfo,
    JunctionStopLineInfo,
    JunctionSurfaceSpanInfo,
    JunctionId,
    Lane,
    LaneDirection,
    LaneId,
    LaneMaterial,
    LaneProfile,
    LaneSection,
    LaneSectionId,
    LaneSpec,
    LaneType,
    MarkingCurveData,
    MeshOptions,
    NetworkMesh,
    Object,
    ObjectId,
    ObjectMarking,
    ObjectOrientation,
    ObjectOutline,
    ObjectRepeat,
    ObjectType,
    OutlineCorner,
    PathPoint,
    Poly3,
    RawXml,
    ReferenceLine,
    RepeatInstance,
    Road,
    RoadEnd,
    RoadId,
    RoadMark,
    RoadMarkColor,
    RoadMarkLine,
    RoadMarkType,
    RoadNetwork,
    RoadStyle,
    Severity,
    Signal,
    SignalId,
    SpanArm,
    SurfaceSpan,
    StencilData,
    StyleLane,
    Surface,
    SurfaceId,
    Waypoint,
    XodrVersion,
    author_clothoid_road,
    build_network_mesh,
    derive_surfaces,
    edit,
    expand_repeat,
    export_glb,
    fit_elevation_profile,
    junction_corners,
    junction_stoplines,
    junction_surface_spans,
    load_xodr,
    parse_xodr,
    save_xodr,
    validate_network,
    version,
    write_xodr,
)

__version__ = version()
__all__ = [name for name in dir() if not name.startswith("_")]
