# Copyright 2026 Robomous
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""RoadMaker: road-network authoring for AV simulation.

C++ kernel with ASAM OpenDRIVE I/O, clothoid authoring, mesh generation,
and glTF export. See https://github.com/robomous/roadmaker.
"""

from ._roadmaker import (  # noqa: F401
    DEFAULT_ADDED_PHASE_SECONDS,
    DEFAULT_PHASE_GREEN_SECONDS,
    DEFAULT_PHASE_YELLOW_SECONDS,
    MAX_SIGNAL_PHASE_DURATION,
    MAX_SIGNAL_PHASE_STATES,
    MAX_SIGNAL_PHASES,
    SIGNAL_APPROACH_WINDOW,
    BoundarySource,
    ContactPoint,
    Control,
    Controller,
    ControllerId,
    CrosswalkData,
    Diagnostic,
    Junction,
    JunctionApproachInfo,
    JunctionController,
    JunctionCorner,
    JunctionCornerInfo,
    JunctionManeuverInfo,
    JunctionPhaseInfo,
    JunctionPhasePlan,
    JunctionStopLineInfo,
    JunctionSurfaceSpanInfo,
    JunctionId,
    Lane,
    LaneDirection,
    LaneId,
    LaneMaterial,
    LaneProfile,
    LaneSection,
    LaneSectionId,
    LaneSpec,
    LaneType,
    Maneuver,
    ManeuverSlide,
    MarkingCurveData,
    MeshOptions,
    NetworkMesh,
    Object,
    ObjectId,
    ObjectMarking,
    ObjectOrientation,
    ObjectOutline,
    ObjectRepeat,
    ObjectType,
    OutlineCorner,
    PathPoint,
    PhaseControllerState,
    PhaseSignalState,
    PhaseState,
    Poly3,
    RawXml,
    ReferenceLine,
    RepeatInstance,
    Road,
    RoadEnd,
    RoadId,
    RoadMark,
    RoadMarkColor,
    RoadMarkLine,
    RoadMarkType,
    RoadNetwork,
    RoadStyle,
    Severity,
    Signal,
    SignalId,
    SignalMount,
    SignalPhase,
    SignalState,
    Signalization,
    SpanArm,
    SurfaceSpan,
    StencilData,
    StyleLane,
    Surface,
    SurfaceId,
    SurfaceNode,
    TurnType,
    Waypoint,
    XodrVersion,
    author_clothoid_road,
    build_network_mesh,
    derive_surfaces,
    edit,
    expand_repeat,
    export_glb,
    fit_elevation_profile,
    junction_corners,
    junction_maneuvers,
    junction_phases,
    junction_signals,
    junction_stoplines,
    junction_surface_spans,
    load_xodr,
    phase_index_at,
    parse_xodr,
    sample_surface_boundary,
    save_xodr,
    surface_boundary_nodes,
    surface_boundary_self_intersects,
    validate_network,
    version,
    write_xodr,
)

__version__ = version()
__all__ = [name for name in dir() if not name.startswith("_")]
