#!/usr/bin/env python3
# Copyright 2026 Robomous
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the committed OSM test fixtures.

Run by hand:  python3 scripts/gen_osm_fixtures.py

WHY THESE ARE FILES ON DISK, like the GIS and lidar fixtures before them: a
reader checked only against bytes the same test just built agrees with itself
about everything, including its own mistakes.  They are generated rather than
downloaded so their provenance is unambiguously ours -- real OSM data is ODbL,
and a committed extract would put a licence obligation in the test tree -- and
generated with the STANDARD LIBRARY ALONE so this script needs no OSM stack.

WHERE THEY ARE.  Amsterdam (UTM 31N / EPSG:32631), the same place the GIS and
lidar fixtures use, and deliberately NOT at (0, 0): a fixture at the origin
hides every false-easting and central-meridian mistake there is.  One way
straddles 3 degrees east -- UTM 31N's central meridian -- so a sign error in the
projection shows up as a discontinuity rather than as nothing.

WHAT THEY MUST COVER.  `district.osm` carries a way for EVERY row of the
mapping table in core/include/roadmaker/osm/tags.hpp, imported and dropped
alike.  That is what makes `EveryClassifiedHighwayValueAppearsInTheFixture` a
real gate: adding a table row without a fixture way fails CI, so the table can
never quietly grow past its own coverage.
"""

from __future__ import annotations

import pathlib

OUT = pathlib.Path(__file__).resolve().parents[1] / "core" / "tests" / "data" / "osm"

# Amsterdam. The scene origin used by the tests sits a few kilometres away, so
# nothing under test is near the projection's origin.
LAT0 = 52.3702
LON0 = 4.8952

# ~1 degree of longitude here is ~68 km; these steps are ~70 m and ~110 m.
DLON = 0.001
DLAT = 0.001

IMPORTED = [
    "motorway",
    "motorway_link",
    "trunk",
    "trunk_link",
    "primary",
    "primary_link",
    "secondary",
    "secondary_link",
    "tertiary",
    "tertiary_link",
    "unclassified",
    "residential",
    "living_street",
    "road",
    "service",
]

DROPPED = [
    "footway",
    "path",
    "cycleway",
    "pedestrian",
    "steps",
    "track",
    "bridleway",
    "corridor",
    "platform",
    "busway",
    "bus_guideway",
    "escape",
    "raceway",
    "construction",
    "proposed",
    "rest_area",
    "services",
    "bus_stop",
    "crossing",
    "elevator",
    "emergency_bay",
    "traffic_island",
]


class Builder:
    """Accumulates nodes and ways, then emits an .osm document."""

    def __init__(self) -> None:
        self.nodes: list[tuple[int, float, float]] = []
        self.ways: list[tuple[int, list[int], list[tuple[str, str]]]] = []
        self._next_node = 1000
        self._next_way = 1

    def node(self, lon: float, lat: float) -> int:
        self._next_node += 1
        self.nodes.append((self._next_node, lon, lat))
        return self._next_node

    def way(self, refs: list[int], tags: list[tuple[str, str]]) -> int:
        self._next_way += 1
        self.ways.append((self._next_way, refs, tags))
        return self._next_way

    def strip(self, row: int, tags: list[tuple[str, str]], points: int = 3) -> int:
        """A short horizontal way on its own row, so nothing shares a node."""
        lat = LAT0 + (row * DLAT)
        refs = [self.node(LON0 + (i * DLON), lat) for i in range(points)]
        return self.way(refs, tags)

    def render(self, note: str) -> str:
        lons = [lon for _, lon, _ in self.nodes]
        lats = [lat for _, _, lat in self.nodes]
        out = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f"<!-- {note}",
            "     Generated by scripts/gen_osm_fixtures.py - do not edit by hand. -->",
            '<osm version="0.6" generator="RoadMaker gen_osm_fixtures.py">',
            f'  <bounds minlat="{min(lats):.7f}" minlon="{min(lons):.7f}"'
            f' maxlat="{max(lats):.7f}" maxlon="{max(lons):.7f}"/>',
        ]
        for node_id, lon, lat in self.nodes:
            out.append(f'  <node id="{node_id}" lat="{lat:.7f}" lon="{lon:.7f}"/>')
        for way_id, refs, tags in self.ways:
            out.append(f'  <way id="{way_id}">')
            out.extend(f'    <nd ref="{ref}"/>' for ref in refs)
            out.extend(f'    <tag k="{k}" v="{v}"/>' for k, v in tags)
            out.append("  </way>")
        out.append("</osm>")
        return "\n".join(out) + "\n"


def district() -> str:
    """Every mapping-table row, plus the tag cases each parser branches on."""
    b = Builder()
    row = 0

    for value in IMPORTED:
        b.strip(row, [("highway", value), ("name", f"{value} way")])
        row += 1

    for value in DROPPED:
        b.strip(row, [("highway", value), ("name", f"{value} way")])
        row += 1

    # maxspeed, one way per branch of parse_maxspeed.
    for spec, name in [
        ("50", "bare-kmh"),
        ("30 mph", "imperial"),
        ("none", "autobahn"),
        ("walk", "unparseable"),
    ]:
        b.strip(row, [("highway", "residential"), ("maxspeed", spec), ("name", name)])
        row += 1

    # oneway, including -1 (which reverses the polyline, not the lanes).
    for spec, name in [("yes", "oneway-yes"), ("-1", "oneway-reverse"), ("no", "oneway-no")]:
        b.strip(row, [("highway", "residential"), ("oneway", spec), ("name", name)])
        row += 1

    # lanes, including the value OSM permits that is not a number.
    for spec, name in [("4", "lanes-4"), ("1;2", "lanes-ambiguous")]:
        b.strip(row, [("highway", "secondary"), ("lanes", spec), ("name", name)])
        row += 1

    # An area outline and a private road: dropped whatever the highway value.
    b.strip(row, [("highway", "pedestrian"), ("area", "yes"), ("name", "plaza")])
    row += 1
    b.strip(row, [("highway", "residential"), ("access", "private"), ("name", "gated")])
    row += 1

    # A roundabout drawn as a closed ring.
    lat = LAT0 + (row * DLAT)
    ring = [b.node(LON0 + (i * DLON * 0.3), lat + (i % 2) * DLAT * 0.2) for i in range(4)]
    b.way(ring + [ring[0]], [("highway", "tertiary"), ("junction", "roundabout")])
    row += 1

    # A way with no highway tag at all: read only when asked for.
    b.strip(row, [("building", "yes"), ("name", "warehouse")])
    row += 1

    # THE CENTRAL-MERIDIAN CASE. UTM 31N's central meridian is 3 degrees east;
    # a way straddling it turns a projection sign error into a visible
    # discontinuity instead of a plausible-looking offset.
    lat = LAT0 + (row * DLAT)
    meridian = [b.node(lon, lat) for lon in (2.9990, 2.9995, 3.0000, 3.0005, 3.0010)]
    b.way(meridian, [("highway", "primary"), ("name", "central meridian")])

    return b.render("RoadMaker OSM fixture: one way per mapping-table row.")


def topology() -> str:
    """A small network whose ways SHARE nodes -- the input the planner needs.

    A plus shape: two ways crossing at a shared middle node (degree 4), each
    arm ending free (degree 1), plus a third way meeting one arm end-to-end
    (degree 2, a plain link).  And an overpass: a bridge way crossing the
    horizontal one at a shared node but tagged layer=1, which must NOT be
    joined -- welding it is invisible in plan view and wrong in every 3D
    consumer downstream.
    """
    b = Builder()

    centre = b.node(LON0, LAT0)
    west = b.node(LON0 - (2 * DLON), LAT0)
    east = b.node(LON0 + (2 * DLON), LAT0)
    north = b.node(LON0, LAT0 + (2 * DLAT))
    south = b.node(LON0, LAT0 - (2 * DLAT))

    b.way([west, centre, east], [("highway", "secondary"), ("name", "east-west")])
    b.way([south, centre, north], [("highway", "secondary"), ("name", "north-south")])

    # End-to-end with the east arm: degree 2, so a plain link and no junction.
    far_east = b.node(LON0 + (4 * DLON), LAT0)
    b.way([east, far_east], [("highway", "secondary"), ("name", "east continuation")])

    # The overpass. It shares `north` with north-south but sits on layer 1.
    over_west = b.node(LON0 - (2 * DLON), LAT0 + (2 * DLAT))
    over_east = b.node(LON0 + (2 * DLON), LAT0 + (2 * DLAT))
    b.way(
        [over_west, north, over_east],
        [("highway", "primary"), ("bridge", "yes"), ("layer", "1"), ("name", "overpass")],
    )

    return b.render("RoadMaker OSM fixture: shared-node topology, including an overpass.")


def deviations() -> str:
    """A polyline whose vertices sit at KNOWN distances from their chord.

    0.4999 m and 0.5001 m from the chord, never 0.5 -- so the simplifier's
    `>` versus `>=` boundary is exercised on both sides rather than assumed.
    A fixture whose values land exactly on the threshold proves nothing about
    which comparison the code uses.
    """
    b = Builder()
    # ~1 degree of latitude is 111 320 m, near enough for a fixture whose
    # assertions are about the metric shape after projection.
    metre_lat = 1.0 / 111_320.0
    lat = LAT0
    refs = [
        b.node(LON0, lat),
        b.node(LON0 + DLON, lat + (0.4999 * metre_lat)),
        b.node(LON0 + (2 * DLON), lat + (0.5001 * metre_lat)),
        b.node(LON0 + (3 * DLON), lat),
    ]
    b.way(refs, [("highway", "residential"), ("name", "deviations")])
    return b.render("RoadMaker OSM fixture: vertices at 0.4999 m and 0.5001 m from the chord.")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in [
        ("district.osm", district()),
        ("topology.osm", topology()),
        ("deviations.osm", deviations()),
    ]:
        path = OUT / name
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path} ({len(text)} bytes)")

    # The refusal fixture: a real PBF magic prefix, so the test asserts the
    # refusal fires on CONTENT-shaped input and not merely on a suffix.
    pbf = OUT / "refused.osm.pbf"
    pbf.write_bytes(b"\x00\x00\x00\x0d\x0a\x09OSMHeader\x18\x2b" + b"\x00" * 16)
    print(f"wrote {pbf} ({pbf.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
