#!/usr/bin/env python3
# Copyright 2026 Robomous
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Embed the US sign-pack artwork as C++ byte arrays.

The sign-face rasteriser (``roadmaker::signs::render_face``, core) composites a
sign's artwork under its legend. The artwork is authored as SVG in
``assets/signs/us/`` after the public-domain US federal sign specifications, and
the kernel rasterises it with nanosvg at whatever size the face needs.

Two constraints shape this script.

* **Core must never link Qt.** ``QSvgRenderer`` is editor-only, and faces are
  baked headless by the glTF exporter and from Python, so the rasteriser has to
  live in the kernel.
* **The kernel does no runtime file IO for assets** (it works from Python and
  CI with no asset directory to locate). So the SVG *source text* is compiled
  in, exactly as ``gen_sign_font.py`` compiles in the font.

That means this script needs no rasteriser at all: it copies bytes. It is
stdlib-only, like ``gen_prop_meshes.py``, so it runs on a bare CI runner.

Run:  python3 scripts/gen_sign_symbols.py
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SVG_DIR = REPO_ROOT / "assets" / "signs" / "us"
GEN_CPP = REPO_ROOT / "core" / "src" / "assets" / "sign_symbols.gen.cpp"

# Bytes per row in the emitted arrays — same shape as sign_font.gen.cpp.
ROW = 16


def _symbol_key(path: Path) -> str:
    """The catalogue key for an artwork file: its stem, e.g. "R1-1"."""
    return path.stem


def _identifier(key: str) -> str:
    """A C++ identifier for `key` ("R6-1-left" -> "k_svg_R6_1_left")."""
    return "k_svg_" + key.replace("-", "_")


def _emit_array(name: str, data: bytes) -> list[str]:
    lines = [f"const unsigned char {name}[] = {{"]
    for start in range(0, len(data), ROW):
        chunk = data[start:start + ROW]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))
    lines.append("};")
    return lines


def main() -> int:
    svgs = sorted(SVG_DIR.glob("*.svg"))
    if not svgs:
        raise SystemExit(f"no artwork found in {SVG_DIR}")

    lines = [
        "// GENERATED by scripts/gen_sign_symbols.py — DO NOT EDIT BY HAND.",
        "// The US sign pack's artwork (assets/signs/us/*.svg, Apache-2.0 original",
        "// work — see ASSETS_LICENSES.md), embedded as SVG source text so the face",
        "// rasteriser has it with no runtime file IO. Regenerate:",
        "//   python3 scripts/gen_sign_symbols.py",
        "",
        '#include "sign_symbols.hpp"',
        "",
        "// clang-format off",
        "namespace roadmaker::signs {",
        "namespace {",
        "",
    ]
    entries = []
    for svg in svgs:
        key = _symbol_key(svg)
        name = _identifier(key)
        lines += _emit_array(name, svg.read_bytes())
        lines.append("")
        entries.append((key, name))

    lines.append("struct Entry {")
    lines.append("  std::string_view key;")
    lines.append("  std::span<const unsigned char> svg;")
    lines.append("};")
    lines.append("")
    lines.append(f"const Entry k_symbols[] = {{")
    for key, name in entries:
        lines.append(f'    {{"{key}", {{{name}, sizeof({name})}}}},')
    lines.append("};")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::span<const unsigned char> symbol_data(std::string_view key) {")
    lines.append("  for (const Entry& entry : k_symbols) {")
    lines.append("    if (entry.key == key) {")
    lines.append("      return entry.svg;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return {};")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace roadmaker::signs")
    lines.append("// clang-format on")
    lines.append("")

    GEN_CPP.parent.mkdir(parents=True, exist_ok=True)
    GEN_CPP.write_text("\n".join(lines), encoding="utf-8")
    total = sum(svg.stat().st_size for svg in svgs)
    print(f"[gen_sign_symbols] embedded {len(svgs)} artwork files "
          f"({total} bytes) → {GEN_CPP}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
