#!/usr/bin/env python3
# Copyright 2026 Robomous
# SPDX-License-Identifier: Apache-2.0

"""Subset the bundled Roboto font and embed it as a C++ byte array.

The sign-face rasteriser (``roadmaker::signs::render_face``, core) draws editable
sign text with stb_truetype, which needs the raw TTF bytes in memory. Rather than
read a file at runtime (core is headless, works from Python and CI with no asset
directory to locate), we compile a *subset* of Roboto straight into the kernel.

Pipeline:

  1. Read the committed, license-clean ``assets/fonts/Roboto-Regular.ttf``
     (Apache-2.0; fetched + verified by ``scripts/fetch_assets.py``, ledgered in
     ASSETS_LICENSES.md and THIRD_PARTY_LICENSES.md).
  2. Subset it to the Latin ranges sign text needs — Basic Latin, Latin-1
     Supplement, Latin Extended-A — with fontTools (dev-time dependency only;
     never built or shipped).
  3. Emit ``core/src/assets/sign_font.gen.cpp`` — the subset TTF as a
     ``static const unsigned char`` array behind ``roadmaker::signs::font_data()``
     (declared in the hand-written ``core/src/assets/sign_font.hpp``).

Regenerate after changing the font or the covered ranges:

    python3 scripts/gen_sign_font.py

Requires fontTools:  pip install fonttools
"""

from __future__ import annotations

import io
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

REPO_ROOT = Path(__file__).resolve().parent.parent
FONT_TTF = REPO_ROOT / "assets" / "fonts" / "Roboto-Regular.ttf"
GEN_CPP = REPO_ROOT / "core" / "src" / "assets" / "sign_font.gen.cpp"

# Codepoint ranges the sign-face rasteriser must cover. Basic Latin carries the
# ASCII sign text; Latin-1 Supplement + Latin Extended-A cover accented town
# names (ä ö ü ß é …) the spec's own @text examples use ("BadAibling", umlauts).
UNICODE_RANGES = [
    (0x0020, 0x007E),  # Basic Latin (printable ASCII)
    (0x00A0, 0x00FF),  # Latin-1 Supplement
    (0x0100, 0x017F),  # Latin Extended-A
]


def _subset_font_bytes() -> bytes:
    """Return the subset Roboto as raw TTF bytes."""
    font = TTFont(str(FONT_TTF))
    options = subset.Options()
    # Keep the tables stb_truetype reads (glyf/loca/cmap/hmtx/head/hhea/maxp);
    # drop layout/hinting extras that only bloat the embedded array. notdef is
    # retained so unmapped codepoints render the .notdef box, never crash.
    options.drop_tables += ["GSUB", "GPOS", "GDEF", "kern", "prep", "fpgm",
                            "cvt", "hdmx", "VDMX", "gasp"]
    options.name_IDs = []
    options.notdef_outline = True
    options.recalc_bounds = True
    options.glyph_names = False
    subsetter = subset.Subsetter(options=options)
    unicodes = []
    for lo, hi in UNICODE_RANGES:
        unicodes.extend(range(lo, hi + 1))
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue()


def _write_cpp(data: bytes) -> None:
    lines = [
        "// GENERATED by scripts/gen_sign_font.py — DO NOT EDIT BY HAND.",
        "// A Latin subset of Roboto-Regular (Apache-2.0; see ASSETS_LICENSES.md",
        "// and THIRD_PARTY_LICENSES.md), embedded so the sign-face rasteriser has",
        "// font glyphs with no runtime file IO. Regenerate:",
        "//   python3 scripts/gen_sign_font.py",
        "",
        '#include "sign_font.hpp"',
        "",
        "// clang-format off — dense generated byte table; left verbatim so CI's",
        "// clang-format --Werror pass does not rewrite it.",
        "// clang-format off",
        "",
        "namespace roadmaker::signs {",
        "namespace {",
        "",
        f"const unsigned char k_font[{len(data)}] = {{",
    ]
    # 16 bytes per row keeps the array readable and the file small.
    for i in range(0, len(data), 16):
        row = ", ".join(str(b) for b in data[i:i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("std::span<const unsigned char> font_data() {")
    lines.append("    return std::span<const unsigned char>(k_font, sizeof(k_font));")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace roadmaker::signs")
    lines.append("")
    lines.append("// clang-format on")
    GEN_CPP.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    if not FONT_TTF.exists():
        raise SystemExit(
            f"missing {FONT_TTF} — run scripts/fetch_assets.py first")
    data = _subset_font_bytes()
    GEN_CPP.parent.mkdir(parents=True, exist_ok=True)
    _write_cpp(data)
    print(f"[gen_sign_font] subset {FONT_TTF.name} → {len(data)} bytes "
          f"→ {GEN_CPP}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
