#!/usr/bin/env python3
# Copyright 2026 Robomous
# SPDX-License-Identifier: Apache-2.0

"""Regenerate the canonical visual-review scenes in assets/samples/.

Three scenes cover the geometry classes the renderer must get right
(docs/standards/product-parity.md — visual acceptance):
  crossing.xodr — endpoint 4-arm junction (fillets on every corner)
  t_attach.xodr — the tee (regenerated by the kernel test suite, not here:
                  core test TJunctionQualityTools.DISABLED_WriteTeeSample)
  overpass.xodr — two roads crossing at different elevations (graded
                  shading + no junction where there is no junction)

CI's visual-artifacts job screenshots these with the editor's
--screenshot mode and uploads the PNGs for human review.

Run from the repo root after `pip install -e python/`:
  python scripts/make_canonical_scenes.py
"""

from __future__ import annotations

from pathlib import Path

import roadmaker as rm

SAMPLES = Path(__file__).resolve().parent.parent / "assets" / "samples"


def crossing() -> None:
    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()
    profile = rm.LaneProfile.two_lane_default()
    # Four arms ending 8 m short of the origin; create_junction joins them.
    arms = [
        [(-80.0, 0.0), (-8.0, 0.0)],
        [(80.0, 0.0), (8.0, 0.0)],
        [(0.0, -80.0), (0.0, -8.0)],
        [(0.0, 80.0), (0.0, 8.0)],
    ]
    for waypoints in arms:
        stack.push(network, rm.edit.create_road(waypoints, profile, ""))
    ends = [
        rm.RoadEnd(network.find_road(str(i + 1)), rm.ContactPoint.END) for i in range(len(arms))
    ]
    stack.push(network, rm.edit.create_junction(network, ends))
    rm.save_xodr(network, str(SAMPLES / "crossing.xodr"), "crossing")
    print(f"wrote {SAMPLES / 'crossing.xodr'}")


def overpass() -> None:
    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()
    profile = rm.LaneProfile.two_lane_default()
    stack.push(network, rm.edit.create_road([(-100.0, 0.0), (100.0, 0.0)], profile, "under"))
    stack.push(network, rm.edit.create_road([(0.0, -100.0), (0.0, 100.0)], profile, "over"))
    over = network.find_road("2")
    # Symmetric rise to +7 m at the crossing: graded approaches shade with
    # their slope (the grade-blind-normal regression is visible here).
    stack.push(
        network,
        rm.edit.set_elevation_profile(
            network,
            over,
            [
                rm.edit.ElevationPoint(0.0, 0.0),
                rm.edit.ElevationPoint(60.0, 0.0),
                rm.edit.ElevationPoint(100.0, 7.0),
                rm.edit.ElevationPoint(140.0, 0.0),
                rm.edit.ElevationPoint(200.0, 0.0),
            ],
        ),
    )
    rm.save_xodr(network, str(SAMPLES / "overpass.xodr"), "overpass")
    print(f"wrote {SAMPLES / 'overpass.xodr'}")


if __name__ == "__main__":
    crossing()
    overpass()
