#!/usr/bin/env python3

# Copyright 2026 Robomous
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerate the canonical visual-review scenes in assets/samples/.

Four scenes cover what the renderer must get right
(docs/standards/product-parity.md — visual acceptance):
  crossing.xodr    — endpoint 4-arm junction (fillets on every corner)
  t_attach.xodr    — the tee (regenerated by the kernel test suite, not here:
                     core test TJunctionQualityTools.DISABLED_WriteTeeSample)
  overpass.xodr    — two roads crossing at different elevations (graded
                     shading + no junction where there is no junction)
  props_scale.xodr — one of every bundled prop along a local street, so prop
                     proportions can be read against a known cross-section
                     (#415; the numbers themselves are gated by
                     core/tests/test_defaults_registry.cpp)

CI's visual-artifacts job screenshots these with the editor's
--screenshot mode and uploads the PNGs for human review.

Run from the repo root after `pip install -e python/`:
  python scripts/make_canonical_scenes.py
"""

from __future__ import annotations

import math
from pathlib import Path

import gen_prop_meshes as props
import roadmaker as rm

SAMPLES = Path(__file__).resolve().parent.parent / "assets" / "samples"

# Prop dimensions come from the mesh author itself rather than a second copy of
# the numbers — there is no Python binding for props::model(), and a sample
# scene that restated the sizes would be exactly the divergence #415 exists to
# stop.
PROPS = {model["id"]: model for model in props.MODELS}


def crossing() -> None:
    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()
    profile = rm.LaneProfile.two_lane_default()
    # Four arms ending 8 m short of the origin; create_junction joins them.
    arms = [
        [(-80.0, 0.0), (-8.0, 0.0)],
        [(80.0, 0.0), (8.0, 0.0)],
        [(0.0, -80.0), (0.0, -8.0)],
        [(0.0, 80.0), (0.0, 8.0)],
    ]
    for waypoints in arms:
        stack.push(network, rm.edit.create_road(waypoints, profile, ""))
    ends = [
        rm.RoadEnd(network.find_road(str(i + 1)), rm.ContactPoint.END) for i in range(len(arms))
    ]
    stack.push(network, rm.edit.create_junction(network, ends))
    rm.save_xodr(network, str(SAMPLES / "crossing.xodr"), "crossing")
    print(f"wrote {SAMPLES / 'crossing.xodr'}")


def overpass() -> None:
    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()
    profile = rm.LaneProfile.two_lane_default()
    stack.push(network, rm.edit.create_road([(-100.0, 0.0), (100.0, 0.0)], profile, "under"))
    stack.push(network, rm.edit.create_road([(0.0, -100.0), (0.0, 100.0)], profile, "over"))
    over = network.find_road("2")
    # Symmetric rise to +7 m at the crossing: graded approaches shade with
    # their slope (the grade-blind-normal regression is visible here).
    stack.push(
        network,
        rm.edit.set_elevation_profile(
            network,
            over,
            [
                rm.edit.ElevationPoint(0.0, 0.0),
                rm.edit.ElevationPoint(60.0, 0.0),
                rm.edit.ElevationPoint(100.0, 7.0),
                rm.edit.ElevationPoint(140.0, 0.0),
                rm.edit.ElevationPoint(200.0, 0.0),
            ],
        ),
    )
    rm.save_xodr(network, str(SAMPLES / "overpass.xodr"), "overpass")
    print(f"wrote {SAMPLES / 'overpass.xodr'}")


def props_scale() -> None:
    """One of every bundled prop along a 150 m local street (#415).

    The point is proportion, not geometry: a 3.0 m lane and a 1.8 m sidewalk
    are the ruler, and every prop is placed at its native size (no scale
    factor), so a mis-sized asset reads wrong at a glance. Plants line the
    verge, the two streetlights stand at the back of the sidewalk with their
    arms turned over the roadway, and the three buildings sit off the
    frontage where their height is comparable to the street width.
    """
    network = rm.RoadNetwork()
    stack = rm.edit.EditStack()
    # The local street IS the §1.2 reference cross-section: one 3.0 m lane and
    # a 1.8 m sidewalk per side, so the right verge starts at t = -4.8.
    stack.push(
        network,
        rm.edit.create_road([(0.0, 0.0), (150.0, 0.0)], rm.LaneProfile.local_road(), "main"),
    )
    road_id = network.find_road("1")

    def place(model: str, s: float, t: float, hdg: float = 0.0) -> None:
        bundled = PROPS[model]
        prop = rm.Object()
        prop.odr_id = str(len(network.objects_of(road_id)) + 1)
        prop.type = getattr(rm.ObjectType, bundled["type"].upper())
        prop.name = model
        prop.s, prop.t, prop.hdg = s, t, hdg
        prop.radius, prop.height = bundled["radius"], bundled["height"]
        stack.push(network, rm.edit.add_object(network, road_id, prop))

    # Plants every 20 m on the verge behind the sidewalk. The oak is the §1.6
    # default street tree; the rest are the band around it.
    for index, model in enumerate(
        ["tree_pine", "tree_oak", "tree_birch", "tree_poplar", "shrub"]
    ):
        place(model, 20.0 + 20.0 * index, -6.5)

    # Luminaires overhang the roadway: a prop's local +x is its heading, so a
    # right-side light needs +90° to swing its arm back over the street.
    place("streetlight_single", 35.0, -5.5, math.pi / 2.0)
    place("streetlight_double", 95.0, -5.5, math.pi / 2.0)

    # Frontage: a two-storey house, a mid-rise and a tower, set back far
    # enough that each one's full height is in frame next to the street.
    for index, model in enumerate(["building_low", "building_mid", "building_tower"]):
        place(model, 25.0 + 45.0 * index, -18.0)

    rm.save_xodr(network, str(SAMPLES / "props_scale.xodr"), "props_scale")
    print(f"wrote {SAMPLES / 'props_scale.xodr'}")


if __name__ == "__main__":
    crossing()
    overpass()
    props_scale()
