// Copyright 2026 Robomous
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Single export path: theme::graphite_amber() -> Starlight CSS custom properties.
//
// WHY A PARSER AND NOT A C++ GENERATOR. The obvious alternative is a generator
// alongside help_style::css(). It was rejected because the site build must not
// require a C++ toolchain: ADR-0009 puts site CI on Linux-only Node runners,
// independent of the C++/CMake matrix, and a generated-artifact dependency
// would couple them. Parsing the initializer keeps theme.cpp the single source
// of truth while leaving the two builds unrelated.
//
// The in-app sheet (editor/resources/help/help.css) is NOT touched: QTextBrowser
// does not support CSS custom properties, so it stays committed pre-substituted
// with flattened hex and byte-gated by test_help_style.cpp.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const source = join(repo, 'editor', 'src', 'theme', 'theme.cpp');
const out = join(here, '..', 'src', 'styles', 'theme.css');

const text = readFileSync(source, 'utf8');

// The initializer block of graphite_amber(), up to its closing `};`.
const start = text.indexOf('const Theme& graphite_amber()');
if (start < 0) throw new Error(`graphite_amber() not found in ${source}`);
const block = text.slice(start, text.indexOf('};', start));

/** `.field = QColor(0xAA, 0xBB, 0xCC),` -> { field: '#aabbcc' } */
const colors = new Map();
const pattern = /\.(\w+)\s*=\s*QColor\(\s*0x([0-9a-fA-F]{2})\s*,\s*0x([0-9a-fA-F]{2})\s*,\s*0x([0-9a-fA-F]{2})\s*\)/g;
for (const m of block.matchAll(pattern)) {
  colors.set(m[1], `#${m[2]}${m[3]}${m[4]}`.toLowerCase());
}

// The tokens the site actually consumes. Named explicitly rather than dumping
// every field, so a rename in theme.cpp fails loudly here instead of silently
// dropping a colour from the site.
const REQUIRED = [
  'bg0', 'bg1', 'bg2', 'border', 'border_strong',
  'text_primary', 'text_secondary', 'accent',
];
const missing = REQUIRED.filter((name) => !colors.has(name));
if (missing.length > 0) {
  throw new Error(
    `theme.cpp no longer defines: ${missing.join(', ')}. ` +
      'Update REQUIRED in scripts/theme-css.mjs to match the renamed fields.',
  );
}

const get = (name) => colors.get(name);
const css = `/* GENERATED by docs-site/scripts/theme-css.mjs from
   editor/src/theme/theme.cpp — theme::graphite_amber().
   Do not edit: run \`npm run theme\`. */
:root[data-theme='dark'] {
  --sl-color-accent-low: ${get('bg2')};
  --sl-color-accent: ${get('accent')};
  --sl-color-accent-high: ${get('text_primary')};
  --sl-color-white: ${get('text_primary')};
  --sl-color-gray-1: ${get('text_primary')};
  --sl-color-gray-2: ${get('text_secondary')};
  --sl-color-gray-3: ${get('border_strong')};
  --sl-color-gray-4: ${get('border')};
  --sl-color-gray-5: ${get('bg2')};
  --sl-color-gray-6: ${get('bg1')};
  --sl-color-black: ${get('bg0')};
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);
console.log(`theme.css written from ${REQUIRED.length} tokens in theme.cpp`);
