// Tests for the bundled low-poly prop meshes (roadmaker::props). The mesh data
// is generated by scripts/gen_prop_meshes.py; these checks lock the invariants
// the kernel mesh builder, exporters, and the editor renderer rely on.

#include "roadmaker/assets/prop_library.hpp"

#include <gtest/gtest.h>

#include <set>
#include <string>

namespace roadmaker::props {
namespace {

TEST(PropLibrary, CatalogueIsNonEmptyAndUnique) {
  const auto& all = ids();
  EXPECT_GE(all.size(), 3u);
  const std::set<std::string> unique(all.begin(), all.end());
  EXPECT_EQ(unique.size(), all.size()) << "prop ids must be unique";
}

TEST(PropLibrary, EveryAdvertisedIdResolves) {
  for (const auto& id : ids()) {
    const PropModel* m = model(id);
    ASSERT_NE(m, nullptr) << "id " << id << " advertised but not resolvable";
    EXPECT_EQ(m->id, id);
  }
}

TEST(PropLibrary, UnknownIdReturnsNull) {
  EXPECT_EQ(model("does_not_exist"), nullptr);
  EXPECT_EQ(model(""), nullptr);
}

TEST(PropLibrary, ModelsAreWellFormed) {
  for (const auto& id : ids()) {
    const PropModel* m = model(id);
    ASSERT_NE(m, nullptr);
    SCOPED_TRACE(id);
    EXPECT_GT(m->height, 0.0);
    EXPECT_GT(m->radius, 0.0);
    ASSERT_FALSE(m->parts.empty());
    for (const PropPart& part : m->parts) {
      // Flat triplets: positions and normals are xyz, one normal per position.
      EXPECT_EQ(part.positions.size() % 3u, 0u);
      EXPECT_EQ(part.positions.size(), part.normals.size());
      EXPECT_EQ(part.indices.size() % 3u, 0u);
      ASSERT_FALSE(part.indices.empty());
      const std::uint32_t vertex_count = static_cast<std::uint32_t>(part.positions.size() / 3u);
      for (std::uint32_t index : part.indices) {
        EXPECT_LT(index, vertex_count) << "index out of range in " << part.name;
      }
      for (float channel : part.color) {
        EXPECT_GE(channel, 0.0f);
        EXPECT_LE(channel, 1.0f);
      }
    }
  }
}

TEST(PropLibrary, PineHasTrunkAndCrown) {
  const PropModel* pine = model("tree_pine");
  ASSERT_NE(pine, nullptr);
  ASSERT_EQ(pine->parts.size(), 2u);
  EXPECT_EQ(pine->parts[0].name, "trunk");
  EXPECT_EQ(pine->parts[1].name, "crown");
}

TEST(PropLibrary, GeometrySitsOnOriginBaseWithinHeight) {
  // A prop's origin is its base centre: z ranges from ~0 up to ~height so it
  // drops onto the road surface without sinking or floating.
  for (const auto& id : ids()) {
    const PropModel* m = model(id);
    ASSERT_NE(m, nullptr);
    SCOPED_TRACE(id);
    double min_z = 1e9;
    double max_z = -1e9;
    for (const PropPart& part : m->parts) {
      for (std::size_t i = 2; i < part.positions.size(); i += 3) {
        min_z = std::min(min_z, part.positions[i]);
        max_z = std::max(max_z, part.positions[i]);
      }
    }
    EXPECT_GE(min_z, -0.01) << "prop should not extend below its base";
    EXPECT_LE(max_z, m->height + 0.01) << "geometry should fit under @height";
  }
}

} // namespace
} // namespace roadmaker::props
