/*
 * Copyright 2026 Robomous
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GIS import (p7-s2, #242), asserted against the COMMITTED fixtures in
// core/tests/data/gis (generated by scripts/gen_gis_fixtures.py).
//
// Everything here reads a real file off disk on purpose. Twice before, a
// feature shipped with tests that would have passed on a build which dropped it
// entirely, because no committed fixture exercised it (#324's `<geoReference>`,
// #390's `rm:surface`/`rm:terrain`). A reader tested only against bytes the
// same test just constructed agrees with itself about everything, including its
// mistakes.

#include "roadmaker/gis/crs.hpp"
#include "roadmaker/gis/layer.hpp"
#include "roadmaker/gis/reproject.hpp"
#include "roadmaker/road/georeference.hpp"
#include "roadmaker/road/terrain.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

using namespace roadmaker;
using namespace roadmaker::gis;

namespace {

std::filesystem::path fixture(const std::string& name) {
  return std::filesystem::path(RM_GIS_FIXTURES_DIR) / name;
}

/// The scene frame the fixtures are imported into: a tmerc on a world origin
/// near the fixtures' own area, which is what p7-s5's editor form produces.
GeoReference amsterdam_scene() {
  GeoReference geo;
  geo.projection = *tmerc_projection(52.3702, 4.8952);
  return geo;
}

bool mentions(const std::vector<Diagnostic>& diagnostics, std::string_view needle) {
  return std::any_of(diagnostics.begin(), diagnostics.end(), [needle](const Diagnostic& d) {
    return d.message.find(needle) != std::string::npos;
  });
}

} // namespace

// --- ★ The fixtures exist and are what they claim --------------------------

TEST(GisCommittedFixtures, EveryFixtureIsPresent) {
  // If this fails, every other test in this file is vacuous — which is exactly
  // how the last two format features shipped with holes in them.
  for (const char* name : {"utm31_image.tif",
                           "utm31_image_lzw.tif",
                           "utm31_image_packbits.tif",
                           "utm31_image_deflate.tif",
                           "wgs84_image.tif",
                           "utm31_dem.tif",
                           "utm31_image.png",
                           "utm31_image.pgw",
                           "utm31_image.prj",
                           "amsterdam.geojson",
                           "utm31_roads.shp",
                           "utm31_roads.dbf",
                           "utm31_roads.prj",
                           "unsupported_crs_roads.shp",
                           "unsupported_crs_roads.prj"}) {
    EXPECT_TRUE(std::filesystem::exists(fixture(name))) << name;
  }
}

// --- Vector: GeoJSON -------------------------------------------------------

TEST(GisVector, ReadsGeoJsonGeometriesAndNames) {
  const Expected<GisVectorParseResult> result = load_gis_vector(fixture("amsterdam.geojson"));
  ASSERT_TRUE(result.has_value()) << result.error().message;
  const GisVectorLayer& layer = result->layer;

  ASSERT_EQ(layer.features.size(), 3U);
  EXPECT_EQ(layer.features[0].geometry, GisFeature::Geometry::Line);
  EXPECT_EQ(layer.features[0].name, "centre line");
  EXPECT_EQ(layer.features[1].geometry, GisFeature::Geometry::Polygon);
  EXPECT_EQ(layer.features[2].geometry, GisFeature::Geometry::Point);

  // RFC 7946 fixes GeoJSON at WGS84 lon/lat; the reader states that rather than
  // leaving the CRS blank, so the import has something to reproject FROM.
  EXPECT_EQ(parse_crs(layer.crs).kind, CrsKind::Geographic);
  EXPECT_NEAR(layer.bounds[0], 4.8500, 1e-9);
  EXPECT_NEAR(layer.bounds[3], 52.4008, 1e-9);
}

TEST(GisVector, RefusesMalformedJsonWithoutThrowing) {
  const std::filesystem::path path =
      std::filesystem::temp_directory_path() / "rm_gis_broken.geojson";
  std::ofstream(path) << "{ this is not json";
  const Expected<GisVectorParseResult> result = load_gis_vector(path);
  EXPECT_FALSE(result.has_value());
  std::filesystem::remove(path);
}

// --- Vector: Shapefile -----------------------------------------------------

TEST(GisVector, ReadsShapefileGeometryAttributesAndPrj) {
  const Expected<GisVectorParseResult> result = load_gis_vector(fixture("utm31_roads.shp"));
  ASSERT_TRUE(result.has_value()) << result.error().message;
  const GisVectorLayer& layer = result->layer;

  ASSERT_EQ(layer.features.size(), 2U);
  EXPECT_EQ(layer.features[0].geometry, GisFeature::Geometry::Line);
  EXPECT_EQ(layer.features[0].vertices.size(), 3U);
  EXPECT_EQ(layer.features[1].vertices.size(), 2U);
  // The .dbf is cosmetic, but reading it wrong would be silently wrong.
  EXPECT_EQ(layer.features[0].name, "Hoofdweg");
  EXPECT_EQ(layer.features[1].name, "Zijstraat");

  // The sibling .prj is what makes the file locatable at all.
  const Crs crs = parse_crs(layer.crs);
  ASSERT_EQ(crs.kind, CrsKind::TransverseMercator);
  EXPECT_DOUBLE_EQ(crs.lon_0, 3.0);
  EXPECT_DOUBLE_EQ(crs.x_0, 500000.0);

  // Coordinates are read little-endian out of a big-endian-framed record.
  EXPECT_NEAR(layer.features[0].vertices[0][0], 628000.0, 1e-6);
  EXPECT_NEAR(layer.features[0].vertices[0][1], 5804000.0, 1e-6);
}

TEST(GisVector, RefusesAShapefileWhoseCrsIsOutOfFamily) {
  const Expected<GisVectorParseResult> result =
      load_gis_vector(fixture("unsupported_crs_roads.shp"));
  // The FILE reads fine — refusal happens at the transform, where both ends are
  // known and the message can name them.
  ASSERT_TRUE(result.has_value()) << result.error().message;
  const Crs source = parse_crs(result->layer.crs);
  EXPECT_EQ(source.kind, CrsKind::Opaque);

  const Expected<CrsTransform> transform = crs_transform(source, scene_crs(amsterdam_scene()));
  ASSERT_FALSE(transform.has_value());
  // The message must identify the CRS the way the user would recognise it. A
  // WKT elided to its first 80 characters shows only the DATUM boilerplate that
  // every WKT shares — which is what this assertion originally caught.
  // Reported in the ORIGINAL casing the user's .prj carries, not the parser's
  // lowercased working copy.
  EXPECT_NE(transform.error().message.find("NAD27_Texas_North"), std::string::npos)
      << transform.error().message;
  EXPECT_NE(transform.error().message.find("Lambert_Conformal_Conic"), std::string::npos)
      << transform.error().message;
}

// --- Raster: GeoTIFF -------------------------------------------------------

TEST(GisRaster, ReadsAnUncompressedGeoTiffWithItsGeoKeysAndPlacement) {
  const Expected<GisRasterParseResult> result = load_gis_raster(fixture("utm31_image.tif"));
  ASSERT_TRUE(result.has_value()) << result.error().message;
  const GisRaster& raster = result->raster;

  EXPECT_EQ(raster.width, 8);
  EXPECT_EQ(raster.height, 6);
  EXPECT_FALSE(raster.elevation);
  EXPECT_EQ(raster.rgba.size(), 8U * 6U * 4U);
  EXPECT_EQ(parse_crs(raster.crs).kind, CrsKind::TransverseMercator);

  // ModelPixelScale's y is positive in the file and NEGATED here, because
  // raster rows run north to south. Getting this wrong mirrors the image.
  EXPECT_DOUBLE_EQ(raster.transform[0], 10.0);
  EXPECT_DOUBLE_EQ(raster.transform[3], -10.0);
  EXPECT_DOUBLE_EQ(raster.transform[4], 628000.0);
  EXPECT_DOUBLE_EQ(raster.transform[5], 5804000.0);
}

TEST(GisRaster, CompressedGeoTiffsDecodeToTheSamePixelsAsTheUncompressedOne) {
  // This is also what validates the fixture generator's own LZW encoder: a
  // wrong encoder produces a stream that decodes to plausible garbage, and only
  // a comparison against known-good pixels says so.
  const Expected<GisRasterParseResult> plain = load_gis_raster(fixture("utm31_image.tif"));
  ASSERT_TRUE(plain.has_value()) << plain.error().message;

  for (const char* name : {"utm31_image_lzw.tif", "utm31_image_packbits.tif"}) {
    const Expected<GisRasterParseResult> compressed = load_gis_raster(fixture(name));
    ASSERT_TRUE(compressed.has_value()) << name << ": " << compressed.error().message;
    EXPECT_EQ(compressed->raster.rgba, plain->raster.rgba) << name;
  }
}

TEST(GisRaster, RefusesDeflateByNameAndCitesTheFollowUp) {
  // Deflate is refused because ADR-0010 declined zlib, not because the decoder
  // failed — so the message must name the compression and where it is tracked.
  const Expected<GisRasterParseResult> result = load_gis_raster(fixture("utm31_image_deflate.tif"));
  ASSERT_FALSE(result.has_value());
  EXPECT_NE(result.error().message.find("Deflate"), std::string::npos) << result.error().message;
  EXPECT_NE(result.error().message.find("#484"), std::string::npos) << result.error().message;
}

TEST(GisRaster, ReadsAWorldFiledPngIdenticallyToTheSameImageAsGeoTiff) {
  const Expected<GisRasterParseResult> png = load_gis_raster(fixture("utm31_image.png"));
  ASSERT_TRUE(png.has_value()) << png.error().message;
  const Expected<GisRasterParseResult> tif = load_gis_raster(fixture("utm31_image.tif"));
  ASSERT_TRUE(tif.has_value()) << tif.error().message;

  EXPECT_EQ(png->raster.width, tif->raster.width);
  EXPECT_EQ(png->raster.rgba, tif->raster.rgba);
  // Two entirely different georeferencing conventions — GeoTIFF tags and a
  // world file — must land the same image in the same place.
  EXPECT_EQ(png->raster.transform, tif->raster.transform);
  EXPECT_EQ(parse_crs(png->raster.crs).kind, CrsKind::TransverseMercator);
}

TEST(GisRaster, RefusesAnImageWithNoGeoreferencingAtAll) {
  // Placing it would mean inventing a position, which is the one thing this
  // module exists not to do.
  const std::filesystem::path lonely = std::filesystem::temp_directory_path() / "rm_gis_lonely.png";
  std::filesystem::copy_file(
      fixture("utm31_image.png"), lonely, std::filesystem::copy_options::overwrite_existing);
  const Expected<GisRasterParseResult> result = load_gis_raster(lonely);
  EXPECT_FALSE(result.has_value());
  std::filesystem::remove(lonely);
}

TEST(GisRaster, ReadsSingleBandFloatAsElevationNotImagery) {
  const Expected<GisRasterParseResult> result = load_gis_raster(fixture("utm31_dem.tif"));
  ASSERT_TRUE(result.has_value()) << result.error().message;
  const GisRaster& raster = result->raster;

  EXPECT_TRUE(raster.elevation);
  EXPECT_TRUE(raster.rgba.empty());
  ASSERT_EQ(raster.band.size(), 8U * 6U);
  ASSERT_TRUE(raster.nodata.has_value());
  EXPECT_DOUBLE_EQ(*raster.nodata, -9999.0);

  // The fixture slopes in both axes: 10 + 2x + 5y. Reading it transposed or
  // upside down would still give a smooth surface, so the corners are checked.
  EXPECT_FLOAT_EQ(raster.band[0], 10.0F);             // top-left  (x=0, y=0)
  EXPECT_FLOAT_EQ(raster.band[7], 10.0F + 14.0F);     // top-right (x=7)
  EXPECT_FLOAT_EQ(raster.band[5 * 8], 10.0F + 25.0F); // bottom-left (y=5)
}

// --- Reprojection ----------------------------------------------------------

TEST(GisReproject, VectorLandsInSceneMetresNearTheOrigin) {
  Expected<GisVectorParseResult> result = load_gis_vector(fixture("utm31_roads.shp"));
  ASSERT_TRUE(result.has_value()) << result.error().message;

  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(result->layer.crs), scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value()) << transform.error().message;

  reproject_vector(result->layer, *transform);

  // The scene origin is Amsterdam and the fixture is a few kilometres away, so
  // reprojected coordinates must be small — thousands of metres, not the
  // millions a raw UTM easting carries. This is the assertion that would catch
  // a transform that silently did nothing.
  for (const GisFeature& feature : result->layer.features) {
    for (const std::array<double, 2>& v : feature.vertices) {
      EXPECT_LT(std::abs(v[0]), 20000.0);
      EXPECT_LT(std::abs(v[1]), 20000.0);
    }
  }
  EXPECT_LT(result->layer.bounds[0], result->layer.bounds[2]);
}

TEST(GisReproject, RoadShapeSurvivesTheTransform) {
  // A reprojection between two Transverse Mercators near the same meridian is
  // very nearly a rigid motion, so segment lengths must be preserved to a few
  // parts in 10 000. A transform that scaled or sheared would pass the
  // "coordinates are small" check above and fail this one.
  Expected<GisVectorParseResult> result = load_gis_vector(fixture("utm31_roads.shp"));
  ASSERT_TRUE(result.has_value());
  const std::array<double, 2> a = result->layer.features[0].vertices[0];
  const std::array<double, 2> b = result->layer.features[0].vertices[1];
  const double before = std::hypot(b[0] - a[0], b[1] - a[1]);

  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(result->layer.crs), scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value());
  reproject_vector(result->layer, *transform);

  const std::array<double, 2> a2 = result->layer.features[0].vertices[0];
  const std::array<double, 2> b2 = result->layer.features[0].vertices[1];
  EXPECT_NEAR(std::hypot(b2[0] - a2[0], b2[1] - a2[1]), before, before * 1e-3);
}

TEST(GisReproject, AnAffineTransformPlacesPixelsWithoutTouchingThem) {
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("utm31_image.tif"));
  ASSERT_TRUE(read.has_value());

  // Same central meridian as the source, so the map is affine.
  GeoReference geo;
  geo.projection = "+proj=tmerc +lat_0=0 +lon_0=3 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m";

  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(read->raster.crs), scene_crs(geo));
  ASSERT_TRUE(transform.has_value()) << transform.error().message;
  ASSERT_TRUE(transform->affine());

  std::vector<Diagnostic> diagnostics;
  const Expected<PlacedRaster> placed = reproject_raster(read->raster, *transform, diagnostics);
  ASSERT_TRUE(placed.has_value()) << placed.error().message;

  EXPECT_EQ(placed->placement, RasterPlacement::Placed);
  EXPECT_EQ(placed->raster.rgba, read->raster.rgba) << "an affine placement must not resample";
  EXPECT_FALSE(mentions(diagnostics, "resampled"));
}

TEST(GisReproject, ANonAffineTransformResamplesAndSaysSo) {
  // A geographic source into a projected scene genuinely curves. Silence here
  // would let a resampled image pass for the original file.
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("wgs84_image.tif"));
  ASSERT_TRUE(read.has_value()) << read.error().message;

  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(read->raster.crs), scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value()) << transform.error().message;
  ASSERT_FALSE(transform->affine());

  std::vector<Diagnostic> diagnostics;
  const Expected<PlacedRaster> placed = reproject_raster(read->raster, *transform, diagnostics);
  ASSERT_TRUE(placed.has_value()) << placed.error().message;

  EXPECT_EQ(placed->placement, RasterPlacement::Resampled);
  EXPECT_TRUE(mentions(diagnostics, "resampled")) << "a resample must be reported";
  EXPECT_GT(placed->raster.width, 0);
  EXPECT_LT(placed->extent[0], placed->extent[2]);
  EXPECT_LT(placed->extent[1], placed->extent[3]);
  // The resampled grid is axis-aligned in the scene frame, which is what the
  // editor's underlay quad depends on.
  EXPECT_DOUBLE_EQ(placed->raster.transform[1], 0.0);
  EXPECT_DOUBLE_EQ(placed->raster.transform[2], 0.0);
}

TEST(GisReproject, AResampledGridHasExactlySquarePixels) {
  // `raster_to_height_field` needs square posts and refuses anything else, so
  // "nearly square" is a silent failure one call downstream. Sizing each axis
  // from its own span produces exactly that — two ceil()s rounding differently
  // — which is how this was found: the worked example turned an 8×6 source into
  // a 9×7 grid and the terrain import refused it.
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("wgs84_image.tif"));
  ASSERT_TRUE(read.has_value());
  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(read->raster.crs), scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value());
  ASSERT_FALSE(transform->affine());

  std::vector<Diagnostic> diagnostics;
  const Expected<PlacedRaster> placed = reproject_raster(read->raster, *transform, diagnostics);
  ASSERT_TRUE(placed.has_value()) << placed.error().message;
  EXPECT_DOUBLE_EQ(placed->raster.transform[0], -placed->raster.transform[3]);
}

// --- Elevation into the scene height field ---------------------------------

TEST(GisReproject, ElevationRasterBecomesAHeightFieldWithRowsFlipped) {
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("utm31_dem.tif"));
  ASSERT_TRUE(read.has_value()) << read.error().message;

  GeoReference geo;
  geo.projection = "+proj=tmerc +lat_0=0 +lon_0=3 +k=0.9996 +x_0=500000 +y_0=0 +datum=WGS84";
  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(read->raster.crs), scene_crs(geo));
  ASSERT_TRUE(transform.has_value()) << transform.error().message;

  std::vector<Diagnostic> diagnostics;
  const Expected<HeightField> field = raster_to_height_field(read->raster, *transform, diagnostics);
  ASSERT_TRUE(field.has_value()) << field.error().message;

  EXPECT_EQ(field->cols, 8U);
  EXPECT_EQ(field->rows, 6U);
  EXPECT_DOUBLE_EQ(field->spacing, 10.0);

  // A HeightField's rows run LOW y first; a raster's run high y first. The
  // fixture is 10 + 2x + 5y with y increasing DOWN the image, so the field's
  // first row must be the raster's LAST — the highest values, not the lowest.
  EXPECT_FLOAT_EQ(static_cast<float>(field->heights[0]), 10.0F + 25.0F);
  EXPECT_FLOAT_EQ(static_cast<float>(field->heights[field->heights.size() - 1]), 10.0F + 14.0F);

  // And it must be usable by the sampler the rest of the kernel already has.
  EXPECT_GT(sample_height(*field, field->origin_x + 5.0, field->origin_y + 5.0), 0.0);
}

TEST(GisReproject, HeightFieldToleratesTheResidueOfAnAffineRoundTrip) {
  // Even an affine placement derives its transform by mapping points through
  // the CRS hub, and at a UTM northing of ~5.8e6 m a double carries roughly
  // 6e-10 of round-trip residue in the off-diagonal terms. An ABSOLUTE epsilon
  // on that quantity is unsound: this test passed on macOS and failed on Linux
  // because the two libm implementations land either side of 1e-9.
  //
  // So: import the same DEM through several scene frames that are all affine to
  // its own, and require every one of them to be accepted as unrotated. What
  // must NOT happen is the answer depending on which machine ran it.
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("utm31_dem.tif"));
  ASSERT_TRUE(read.has_value()) << read.error().message;

  for (const char* projection : {
           "+proj=tmerc +lat_0=0 +lon_0=3 +k=0.9996 +x_0=500000 +y_0=0 +datum=WGS84",
           "+proj=tmerc +lat_0=0 +lon_0=3 +k=1 +x_0=0 +y_0=0 +datum=WGS84",
           "+proj=utm +zone=31 +datum=WGS84 +units=m",
       }) {
    GeoReference geo;
    geo.projection = projection;
    const Expected<CrsTransform> transform =
        crs_transform(parse_crs(read->raster.crs), scene_crs(geo));
    ASSERT_TRUE(transform.has_value()) << projection;
    ASSERT_TRUE(transform->affine()) << projection;

    std::vector<Diagnostic> diagnostics;
    const Expected<HeightField> field =
        raster_to_height_field(read->raster, *transform, diagnostics);
    EXPECT_TRUE(field.has_value())
        << projection << ": " << (field.has_value() ? "" : field.error().message);
  }
}

TEST(GisReproject, ImageryIsRefusedAsTerrainWithAnActionableMessage) {
  const Expected<GisRasterParseResult> read = load_gis_raster(fixture("utm31_image.tif"));
  ASSERT_TRUE(read.has_value());
  const Expected<CrsTransform> transform =
      crs_transform(parse_crs(read->raster.crs), scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value());

  std::vector<Diagnostic> diagnostics;
  const Expected<HeightField> field = raster_to_height_field(read->raster, *transform, diagnostics);
  ASSERT_FALSE(field.has_value());
  EXPECT_NE(field.error().message.find("single-band"), std::string::npos) << field.error().message;
}

// --- Dispatch --------------------------------------------------------------

TEST(GisImport, ExtensionPredicatesMatchWhatTheLoadersActuallyAccept) {
  // The editor builds its file-dialog filters from these, so a predicate that
  // offers a file the loader then refuses shows up to the user as randomness.
  EXPECT_TRUE(is_vector_extension("a.geojson"));
  EXPECT_TRUE(is_vector_extension("a.SHP"));
  EXPECT_FALSE(is_vector_extension("a.tif"));
  EXPECT_TRUE(is_raster_extension("a.tif"));
  EXPECT_TRUE(is_raster_extension("a.JPEG"));
  EXPECT_FALSE(is_raster_extension("a.shp"));
}

TEST(GisImport, AnUnsupportedExtensionIsRefusedByNameWithItsFollowUp) {
  const Expected<GisVectorParseResult> vector = load_gis_vector(fixture("nope.gpkg"));
  ASSERT_FALSE(vector.has_value());
  EXPECT_NE(vector.error().message.find("#486"), std::string::npos) << vector.error().message;

  const Expected<GisRasterParseResult> raster = load_gis_raster(fixture("nope.jp2"));
  ASSERT_FALSE(raster.has_value());
  EXPECT_NE(raster.error().message.find("#484"), std::string::npos) << raster.error().message;
}

TEST(GisImport, AMissingFileIsAFileNotFoundRatherThanAParseFailure) {
  const Expected<GisVectorParseResult> result = load_gis_vector(fixture("absent.geojson"));
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code, ErrorCode::FileNotFound);
}
