/*
 * Copyright 2026 Robomous
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Lidar import (p7-s3, #243), asserted against the COMMITTED fixtures in
// core/tests/data/lidar (generated by scripts/gen_lidar_fixtures.py, except the
// .laz — see core/tests/tools/make_laz_fixture.cpp).
//
// Everything here reads a real file off disk on purpose, for the reason
// test_gis_import.cpp states: a reader tested only against bytes the same test
// just constructed agrees with itself about everything, including its mistakes.

#include "roadmaker/gis/crs.hpp"
#include "roadmaker/lidar/point_cloud.hpp"
#include "roadmaker/road/georeference.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <numbers>
#include <string>
#include <string_view>
#include <vector>

using namespace roadmaker;
using namespace roadmaker::lidar;

namespace {

std::filesystem::path fixture(const std::string& name) {
  return std::filesystem::path(RM_LIDAR_FIXTURES_DIR) / name;
}

/// The scene frame the fixtures import into: a tmerc on a world origin near the
/// tile, which is what p7-s5's editor form produces.
GeoReference amsterdam_scene() {
  GeoReference geo;
  geo.projection = *tmerc_projection(52.3702, 4.8952);
  return geo;
}

bool mentions(const std::vector<Diagnostic>& diagnostics, std::string_view needle) {
  return std::any_of(diagnostics.begin(), diagnostics.end(), [needle](const Diagnostic& d) {
    return d.message.find(needle) != std::string::npos;
  });
}

/// Points sorted into a canonical order, so two readings of the same tile can be
/// compared without depending on file order.
std::vector<std::array<double, 3>> sorted_points(const PointCloud& cloud) {
  std::vector<std::array<double, 3>> points;
  points.reserve(cloud.size());
  for (std::size_t i = 0; i < cloud.size(); ++i) {
    points.push_back(cloud.point(i));
  }
  std::sort(points.begin(), points.end());
  return points;
}

} // namespace

// --- ★ The fixtures exist ---------------------------------------------------

TEST(LidarCommittedFixtures, EveryFixtureIsPresent) {
  // If this fails, every other test in this file is vacuous — which is exactly
  // how three earlier format features shipped with holes in them.
  for (const char* name : {"amsterdam_tile.las",
                           "amsterdam_tile_14.las",
                           "amsterdam_tile_extra.las",
                           "amsterdam_tile.laz",
                           "unsupported_crs.las",
                           "no_crs.las"}) {
    EXPECT_TRUE(std::filesystem::exists(fixture(name))) << name;
  }
}

// --- Reading a tile ---------------------------------------------------------

TEST(LidarImport, ReadsALas12TileWithGeoTiffKeys) {
  const auto result = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(result.has_value()) << (result ? "" : result.error().message);

  EXPECT_EQ(result->cloud.size(), 388U);
  EXPECT_EQ(result->cloud.source_count, 388U);
  EXPECT_EQ(result->cloud.stride, 1U);
  EXPECT_EQ(result->cloud.crs, "EPSG:32631");

  // The tile is 100 × 80 m at a UTM easting/northing of Amsterdam. Bounds are
  // absolute, in the file's own frame, before any reprojection.
  EXPECT_NEAR(result->cloud.bounds[0], 628000.0, 1e-3);
  EXPECT_NEAR(result->cloud.bounds[1], 5803000.0, 1e-3);
  EXPECT_NEAR(result->cloud.bounds[3], 628100.0, 1e-3);
  EXPECT_NEAR(result->cloud.bounds[4], 5803080.0, 1e-3);
}

TEST(LidarImport, ReadsALas14TileWithWktAndTheWidePointCount) {
  // LAS 1.4 + point format 6 changes four things at once: the header grows to
  // 375 bytes, the point count moves to a 64-bit field (with the legacy one
  // required to be zero), the return field widens, and classification is
  // promoted out of a bit field into a whole byte. A reader that got the header
  // size right and the count wrong would report zero points.
  const auto result = load_point_cloud(fixture("amsterdam_tile_14.las"));
  ASSERT_TRUE(result.has_value()) << (result ? "" : result.error().message);

  EXPECT_EQ(result->cloud.size(), 388U);
  EXPECT_EQ(result->cloud.source_count, 388U);
  EXPECT_NE(result->cloud.crs.find("UTM zone 31N"), std::string::npos) << result->cloud.crs;
}

TEST(LidarImport, TheTwoVersionsOfTheSameTileAgree) {
  // Same points, written at LAS 1.2 with GeoTIFF keys and at LAS 1.4 with WKT.
  // Everything about how they are stored differs; nothing about what they mean
  // does.
  const auto twelve = load_point_cloud(fixture("amsterdam_tile.las"));
  const auto fourteen = load_point_cloud(fixture("amsterdam_tile_14.las"));
  ASSERT_TRUE(twelve.has_value());
  ASSERT_TRUE(fourteen.has_value());

  const auto a = sorted_points(twelve->cloud);
  const auto b = sorted_points(fourteen->cloud);
  ASSERT_EQ(a.size(), b.size());
  for (std::size_t i = 0; i < a.size(); ++i) {
    for (std::size_t axis = 0; axis < 3; ++axis) {
      EXPECT_NEAR(a[i][axis], b[i][axis], 1e-3) << "point " << i << " axis " << axis;
    }
  }
}

TEST(LidarImport, RecordsLongerThanTheirFormatAreStepped) {
  // Extra bytes past the format's own fields are legal and common. A reader
  // stepping by the FORMAT's length rather than the HEADER's reads garbage from
  // the second point onward — and garbage that still parses as coordinates.
  const auto extra = load_point_cloud(fixture("amsterdam_tile_extra.las"));
  const auto plain = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(extra.has_value()) << (extra ? "" : extra.error().message);
  ASSERT_TRUE(plain.has_value());

  const auto a = sorted_points(extra->cloud);
  const auto b = sorted_points(plain->cloud);
  ASSERT_EQ(a.size(), b.size());
  for (std::size_t i = 0; i < a.size(); ++i) {
    EXPECT_NEAR(a[i][0], b[i][0], 1e-3) << "point " << i;
    EXPECT_NEAR(a[i][1], b[i][1], 1e-3) << "point " << i;
  }
}

TEST(LidarImport, LazDecodesIdenticallyToLas) {
  // ★ THE ORACLE FOR THE WHOLE LAZ PATH. The two files hold the same tile, one
  // compressed and one not, and both are committed — so this compares against
  // fixed bytes rather than against something the test just produced.
  const auto plain = load_point_cloud(fixture("amsterdam_tile.las"));
  const auto packed = load_point_cloud(fixture("amsterdam_tile.laz"));
  ASSERT_TRUE(plain.has_value()) << (plain ? "" : plain.error().message);
  ASSERT_TRUE(packed.has_value()) << (packed ? "" : packed.error().message);

  ASSERT_EQ(packed->cloud.size(), plain->cloud.size());
  const auto a = sorted_points(plain->cloud);
  const auto b = sorted_points(packed->cloud);
  for (std::size_t i = 0; i < a.size(); ++i) {
    for (std::size_t axis = 0; axis < 3; ++axis) {
      // LAZ is LOSSLESS: it stores the same 32-bit integers, so the decoded
      // coordinates are exactly equal, not merely close. Any tolerance here
      // would hide a scale/offset mistake.
      EXPECT_DOUBLE_EQ(a[i][axis], b[i][axis]) << "point " << i << " axis " << axis;
    }
  }
  ASSERT_EQ(packed->cloud.classification.size(), plain->cloud.classification.size());
  EXPECT_EQ(packed->cloud.classification, plain->cloud.classification);

  // ★ AND THE CRS, WHICH IS WHERE THIS ALMOST SHIPPED WITH A HOLE. laz-perf's
  // writer emits its own header and only its own VLRs, so the first version of
  // the fixture tool produced a .laz with no coordinate system at all — unlike
  // every .laz in the world, and leaving the reader's VLR walk (which runs
  // BEFORE decompression) untested on a compressed file. Comparing points and
  // classification alone passed happily on it.
  EXPECT_EQ(packed->cloud.crs, plain->cloud.crs);
  EXPECT_FALSE(packed->cloud.crs.empty());
}

// --- Classification ---------------------------------------------------------

TEST(LidarImport, LegacyFormatsMaskTheClassificationBits) {
  // ★ In formats 0-5 the class is bits 0-4 of byte 15; bits 5-7 are synthetic,
  // key-point and withheld. The last point of every legacy fixture carries the
  // withheld bit, so a reader that forgets the mask reports 0x82 = 130 for what
  // is a class-5 vegetation return — and would silently drop it from any
  // classification-driven fit.
  const auto result = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(result.has_value());
  ASSERT_EQ(result->cloud.classification.size(), result->cloud.size());

  for (const std::uint8_t value : result->cloud.classification) {
    EXPECT_LE(value, 31U) << "a class past 31 means the flag bits leaked in";
  }
  EXPECT_NE(std::find(result->cloud.classification.begin(),
                      result->cloud.classification.end(),
                      kGroundClass),
            result->cloud.classification.end());
}

TEST(LidarImport, ClassificationSurvivesTheFormatPromotion) {
  // Formats 6-10 moved the class to byte 16 whole. The two fixtures must
  // therefore report the same multiset of classes despite reading a different
  // byte with a different rule.
  const auto twelve = load_point_cloud(fixture("amsterdam_tile.las"));
  const auto fourteen = load_point_cloud(fixture("amsterdam_tile_14.las"));
  ASSERT_TRUE(twelve.has_value());
  ASSERT_TRUE(fourteen.has_value());

  std::vector<std::uint8_t> a = twelve->cloud.classification;
  std::vector<std::uint8_t> b = fourteen->cloud.classification;
  std::sort(a.begin(), a.end());
  std::sort(b.begin(), b.end());
  EXPECT_EQ(a, b);
}

// --- Decimation -------------------------------------------------------------

TEST(LidarImport, DecimationHonoursTheBudgetAndSaysSo) {
  LidarReadOptions options;
  options.max_points = 100;
  const auto result = load_point_cloud(fixture("amsterdam_tile.las"), options);
  ASSERT_TRUE(result.has_value()) << (result ? "" : result.error().message);

  EXPECT_LE(result->cloud.size(), options.max_points);
  EXPECT_GT(result->cloud.stride, 1U);
  EXPECT_EQ(result->cloud.source_count, 388U);
  // ★ Said out loud, always. A cloud silently reduced looks like a sparse
  // survey rather than a decimated one, and every judgement about coverage
  // made from it would be wrong.
  EXPECT_TRUE(mentions(result->diagnostics, "kept 1 point in"));
}

TEST(LidarImport, DecimationIsDeterministic) {
  // Two reads of the same file must agree exactly. A random sample would not,
  // and a scene reopened tomorrow would not be the scene saved today.
  LidarReadOptions options;
  options.max_points = 100;
  const auto first = load_point_cloud(fixture("amsterdam_tile.las"), options);
  const auto second = load_point_cloud(fixture("amsterdam_tile.las"), options);
  ASSERT_TRUE(first.has_value());
  ASSERT_TRUE(second.has_value());
  EXPECT_EQ(first->cloud.xyz, second->cloud.xyz);
}

TEST(LidarImport, AWholeTileUnderTheBudgetIsNotDecimated) {
  const auto result = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(result.has_value());
  EXPECT_EQ(result->cloud.stride, 1U);
  EXPECT_FALSE(mentions(result->diagnostics, "kept 1 point in"));
}

// --- The CRS ----------------------------------------------------------------

TEST(LidarImport, AnUnsupportedCrsIsRefusedByNameAndCitesItsIssue) {
  const auto result = load_point_cloud(fixture("unsupported_crs.las"));
  ASSERT_TRUE(result.has_value()) << "the FILE is readable; only the transform is refused";

  const gis::Crs source = gis::parse_crs(result->cloud.crs);
  const gis::Crs scene = gis::scene_crs(amsterdam_scene());
  const auto transform = gis::crs_transform(source, scene);
  ASSERT_FALSE(transform.has_value());

  // "Unsupported" on its own tells a user nothing about where the boundary is
  // or whether it is moving. The whole point of computing a bounded family is
  // being able to say precisely what fell outside it.
  EXPECT_NE(transform.error().message.find("#485"), std::string::npos) << transform.error().message;
  EXPECT_NE(gis::describe_crs(source).find("NAD27"), std::string::npos)
      << gis::describe_crs(source);
}

TEST(LidarImport, ATileWithNoStatedCrsWarnsRatherThanGuessing) {
  const auto result = load_point_cloud(fixture("no_crs.las"));
  ASSERT_TRUE(result.has_value()) << (result ? "" : result.error().message);
  EXPECT_TRUE(result->cloud.crs.empty());
  EXPECT_TRUE(mentions(result->diagnostics, "states no coordinate reference system"));
}

// --- Reprojection -----------------------------------------------------------

TEST(LidarImport, ReprojectionLandsTheTileInSceneMetres) {
  auto result = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(result.has_value());

  const auto transform =
      gis::crs_transform(gis::parse_crs(result->cloud.crs), gis::scene_crs(amsterdam_scene()));
  ASSERT_TRUE(transform.has_value()) << (transform ? "" : transform.error().message);

  const double before_z = result->cloud.point(0)[2];
  reproject_point_cloud(result->cloud, *transform);

  // The scene origin is inside the tile, so scene coordinates are small — the
  // whole reason p7-s5's frame is a tmerc on the origin.
  EXPECT_LT(std::abs(result->cloud.bounds[0]), 2000.0);
  EXPECT_LT(std::abs(result->cloud.bounds[1]), 2000.0);
  // ★ THE TILE KEEPS ITS SIZE BUT NOT ITS AXIS-ALIGNED BOX, AND THE DIFFERENCE
  // IS GRID CONVERGENCE — not error.
  //
  // UTM zone 31's central meridian is 3° E and the scene's is 4.8952° E, so at
  // latitude 52.37° the two grids' norths differ by about Δλ·sin(φ) = 1.50°.
  // The tile arrives ROTATED by that angle, and an axis-aligned bounding box is
  // not rotation-invariant: a 100 × 80 m rectangle turned 1.5° has a box of
  // 100·cos + 80·sin ≈ 102.1 by 100·sin + 80·cos ≈ 82.6. Asserting the box was
  // preserved would be asserting that this real effect does not happen.
  //
  // So the assertion is on the DIAGONAL, which a rigid motion does preserve.
  const double before_diagonal = std::hypot(100.0, 80.0);
  const double box_x = result->cloud.bounds[3] - result->cloud.bounds[0];
  const double box_y = result->cloud.bounds[4] - result->cloud.bounds[1];
  constexpr double kConvergenceDeg = 1.4999;
  const double turned = kConvergenceDeg * std::numbers::pi / 180.0;
  EXPECT_NEAR(box_x, (100.0 * std::cos(turned)) + (80.0 * std::sin(turned)), 0.05);
  EXPECT_NEAR(box_y, (100.0 * std::sin(turned)) + (80.0 * std::cos(turned)), 0.05);

  // And the tile's own extent is unchanged: the greatest distance between any
  // TWO POINTS, which no rotation touches. Measuring from the bounding box's
  // corner instead would not do — after a rotation that corner is outside the
  // tile, so the longest ray from it is longer than the tile's own diagonal.
  // Relative, because this has been through the CRS hub, and an absolute
  // epsilon on a projected quantity is a platform test (PR #488, twice).
  double furthest = 0.0;
  for (std::size_t i = 0; i < result->cloud.size(); ++i) {
    const std::array<double, 3> a = result->cloud.point(i);
    for (std::size_t j = i + 1; j < result->cloud.size(); ++j) {
      const std::array<double, 3> b = result->cloud.point(j);
      furthest = std::max(furthest, std::hypot(a[0] - b[0], a[1] - b[1]));
    }
  }
  EXPECT_NEAR(furthest, before_diagonal, before_diagonal * 1e-3);
  // ★ Z IS UNTOUCHED. Every CRS in the supported family shares one ellipsoid
  // and none of them is a vertical datum, so moving heights would be a datum
  // shift — which ADR-0010 refuses to perform or imply.
  EXPECT_DOUBLE_EQ(result->cloud.point(0)[2], before_z);
}

TEST(LidarImport, PointsStayFaithfulThroughTheFloatOffsetRepresentation) {
  // ★ THE PRECISION TEST. A UTM northing near 5.8e6 has a float quantum of
  // about half a metre, so a cloud stored in absolute floats would terrace
  // itself. Storing offsets from a double origin keeps the detail; this asserts
  // the round trip through that representation is good to a millimetre, at the
  // full UTM magnitude, BEFORE any reprojection shrinks the numbers.
  const auto result = load_point_cloud(fixture("amsterdam_tile.las"));
  ASSERT_TRUE(result.has_value());

  bool saw_a_big_northing = false;
  for (std::size_t i = 0; i < result->cloud.size(); ++i) {
    const std::array<double, 3> world = result->cloud.point(i);
    saw_a_big_northing = saw_a_big_northing || world[1] > 5.0e6;
    // The fixture is on a 5 m lattice from the tile corner, so every coordinate
    // is an exact multiple of 5 away from it.
    const double dx = world[0] - 628000.0;
    EXPECT_NEAR(dx, std::round(dx / 5.0) * 5.0, 1e-3) << "point " << i;
  }
  EXPECT_TRUE(saw_a_big_northing) << "the fixture must actually sit at UTM magnitude, or this "
                                     "test proves nothing";
}

// --- Refusals ---------------------------------------------------------------

TEST(LidarImport, TheExtensionPredicateAgreesWithTheLoader) {
  // The file-dialog filter and the reader must not be able to disagree about
  // what is openable.
  EXPECT_TRUE(is_point_cloud_extension("tile.las"));
  EXPECT_TRUE(is_point_cloud_extension("tile.LAZ"));
  EXPECT_FALSE(is_point_cloud_extension("tile.e57"));
  EXPECT_FALSE(is_point_cloud_extension("tile.tif"));

  const auto refused = load_point_cloud(fixture("amsterdam_tile.e57"));
  ASSERT_FALSE(refused.has_value());
  EXPECT_NE(refused.error().message.find(".e57"), std::string::npos) << refused.error().message;
}

TEST(LidarImport, AMissingFileIsRefusedNotCrashed) {
  const auto refused = load_point_cloud(fixture("nope.las"));
  EXPECT_FALSE(refused.has_value());
}

TEST(LidarImport, SomethingThatIsNotALasFileIsRefusedBySignature) {
  const auto refused =
      load_point_cloud(std::filesystem::path(RM_GIS_FIXTURES_DIR) / "amsterdam.geojson");
  ASSERT_FALSE(refused.has_value());
  // Refused for its extension before its bytes are ever read, which is the
  // cheaper and more accurate answer.
  EXPECT_NE(refused.error().message.find(".geojson"), std::string::npos) << refused.error().message;
}

TEST(LidarImport, ATruncatedFileIsRefusedRatherThanReadPastTheEnd) {
  // Through the public API rather than the private header parser: the private
  // symbols are not exported, and a shared-kernel build would fail to link a
  // test that reached for them (the p5-s3 scar).
  const std::filesystem::path truncated =
      std::filesystem::temp_directory_path() / "rm_truncated_fixture.las";
  {
    std::ofstream out(truncated, std::ios::binary);
    out << "LASF" << std::string(40, '\0');
  }
  const auto refused = load_point_cloud(truncated);
  std::filesystem::remove(truncated);

  ASSERT_FALSE(refused.has_value());
  EXPECT_NE(refused.error().message.find("too short"), std::string::npos)
      << refused.error().message;
}

TEST(LidarImport, AHeaderPromisingMorePointsThanTheFileHoldsIsReportedNotTrusted) {
  // A tile cut short by a failed transfer is common, and reading past the end
  // of it would be the kind of bug an offset table makes look like data.
  std::ifstream input(fixture("amsterdam_tile.las"), std::ios::binary);
  ASSERT_TRUE(input.good());
  std::string bytes((std::istreambuf_iterator<char>(input)), std::istreambuf_iterator<char>());
  input.close();
  bytes.resize(bytes.size() - (34 * 100)); // lose the last hundred records

  const std::filesystem::path cut = std::filesystem::temp_directory_path() / "rm_cut_fixture.las";
  {
    std::ofstream out(cut, std::ios::binary);
    out.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
  }
  const auto result = load_point_cloud(cut);
  std::filesystem::remove(cut);

  ASSERT_TRUE(result.has_value()) << (result ? "" : result.error().message);
  EXPECT_EQ(result->cloud.size(), 288U);
  EXPECT_TRUE(mentions(result->diagnostics, "looks truncated"));
}
